### PR TITLE
add  zip upload  plugin

### PR DESCRIPTION
**Pull request by zengzhubuchitian**
add  zip upload  plugin

### CODE REVIEW

**Comment by pd4d10** [comment]
Hi, thanks for the contribution!

Could you please introduce a bit about this plugin's feature?

**Comment by zengzhubuchitian** [comment]
> Hi, thanks for the contribution!
> 
> Could you please introduce a bit about this plugin's feature?

   

>When I used the image upload function, I found that bytemd did not support zip uploads, which is an important requirement in my project,  so I developed a plugin for zip uploads.

>How to use:
>By providing a function that returns a download url as a string, user can click the zip upload icon to select a zip file and add the file name with link in the content
>See more usages in the  [README](https://github.com/zengzhubuchitian/bytemd/tree/main/packages/plugin-zip#readme)

**Comment by pd4d10** [comment]
Sounds good!

> By providing a function that returns a download url as a string, user can click the zip upload icon to select a zip file and add the file name with link in the content

It looks more like a business specific feature than a general one.

Perhaps you can maintain this plugin in a separated repo, and we can add a section named Community plugins after [Official plugins](https://github.com/bytedance/bytemd#official-plugins) in README, and add it there.

What do you think?

**Comment by zengzhubuchitian** [comment]
> It looks more like a business specific feature than a general one.
> 
> Perhaps you can maintain this plugin in a separated repo, and we can add a section named Community plugins after [Official plugins](https://github.com/bytedance/bytemd#official-plugins) in README, and add it there.

Fine, thanks

**Pull request closed without merging**
